default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: csv_importer_development

test:
  <<: *default
  database: csv_importer_test

production:
  <<: *default
  database: csv_importer_production
